# Generated by Django 4.2.1 on 2023-05-26 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=610)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
