# Generated by Django 4.2.1 on 2023-05-19 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_join_date', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
