# Generated by Django 4.2.1 on 2023-05-19 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
