# Generated by Django 4.2.1 on 2023-05-12 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usesrname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=610)),
                ('create_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
