# Generated by Django 4.2.1 on 2023-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Password_Storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='usesrname',
            new_name='username',
        ),
    ]
